# Change these first
owner: octane-agency # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: The Octane Server
    url: https://host.theoctaneserver.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.theoctaneserver.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: http://static.theoctaneagency.com/octane-badge/octane-o.svg
  name: Octane Server Status
  introTitle: "Octane Server Status"
  introMessage: Please email or call us if your Octane managed website is down. See our [Support](https://theoctaneagency.com/support/) page for details.
  navbar:
    - title: Status
      href: /
    - title: Octane Marketing
      href: https://www.theoctaneagency.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
